//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Basket
    {
        public int id { get; set; }
        public string name { get; set; }
        public Nullable<int> id_genre { get; set; }
        public string author { get; set; }
        public Nullable<int> price { get; set; }
        public Nullable<int> quantity { get; set; }
        public string cover { get; set; }
    
        public virtual BookShop BookShop { get; set; }
        public virtual Genre Genre { get; set; }
    }
}
